apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "edge-orders.fullname" . }}
  labels:
    {{- include "edge-orders.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "edge-orders.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "edge-orders.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "edge-orders.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          volumeMounts:
            - name: secure-store-props
              mountPath: "/etc/edge/ephemeral"
              readOnly: true
            - name: api-configuration
              mountPath: "/etc/edge/api"
              readOnly: true
          env:
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  key: DB_DATABASE
                  name: db-connect-modules
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: DB_HOST
                  name: db-connect-modules
            - name: DB_MAXPOOLSIZE
              value: {{ .Values.dbMaxPoolSize | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: db-connect-modules
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  key: DB_PORT
                  name: db-connect-modules
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: DB_USERNAME
                  name: db-connect-modules
            - name: ENV
              valueFrom:
                secretKeyRef:
                  key: ENV
                  name: db-connect-modules      
            - name: JAVA_OPTIONS
              value: {{ .Values.javaOptions | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: secure-store-props
        secret:
          secretName: ephemeral-properties
      - name: api-configuration
        secret:
          secretName: apiconfiguration
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
